---
title: "Instructions for user tests of Sprout"
---

::: callout-warning
🚧 This section is still in active development and is subject to changes
🚧
:::

This document provides the context and instructions for users who we ask
to come and test out a demo of Sprout. We intended to use this document
so that a user can read before they come and do a user test.

For this user test, we've made a basic case example that includes three
simple test data files.

## About Sprout

Sprout is a component of the Seedcase software ecosystem, which is a
framework for an open and scalable infrastructure for health data. The
Seedcase ecosystem aims to enable researchers to build, manage, and
(legally) share health data using modern best practices in data
engineering.

Sprout is the component for building or "growing" data and aims to:

> Take data created or collected for research studies and "grow" it in a
> structured way using modern best practices for storing data along with
> its metadata.

## Context

Imagine you are a researcher collecting data on diabetes patients and
their physical activity. You want to save and structure your data to
ease the process of:

1.  adding more data to your dataset, when more has been collected, and

2.  analysing the data later on.

You have collected the data across two time periods (in 2023 and 2024),
resulting in a longitudinal study of the same individuals, who tracked
their exercise in March of 2023 and 2024.

You have two types of files with data:

1.  A `patients` file that describes the patients and includes their
    age, sex, height, weight, and diabetes type. The file is called
    `patients.csv`.

| id  | age | sex | height | weight | diabetes_type |
|-----|-----|-----|--------|--------|---------------|
| 1   | 54  | F   | 167.5  |  70.3  | Type 1        |
| 2   | 66  | M   | 175    |  80.5  | Type 2        |

: Showing the first two rows in the `patients.csv` file.

2.  Two `physical_activity` files that describe their physical activity
    patterns, such as when they did activities, what type of activity,
    and for how long. The files are called `physical_activity_2023.csv`
    and `physical_activity_2024.csv`.

| id  | physical_activity | duration | date       |
|-----|-------------------|----------|------------|
| 1   | run               | 10       | 01-03-2024 |
| 2   | walk              | 25       | 02-04-2024 |

: Showing the first two rows in the `physical_activity_2024.csv` file.

Since you want to grow your data in a structured way, you decide to try
out Sprout for handling your data.

## Tasks

We want you to do some tasks, that you'll read about below. As you do
it, we want you to tell us your inner dialogue and thought process on
what you're doing and what makes sense, doesn't make sense, is
confusing, or is something you like.

Throughout, we will refrain from explaining and helping you too much.

::: callout-note
An important aspect of user testing for you as the user is that **there
are no right or wrong answers.** We are trying to learn how to build a
better tool for you and others like you. So give honest, constructive
feedback!

If something is unclear to you, it is a great oppurtunity for us to
learn how to make it clearer going forward - this is exactly why user
tests are so helpful for us!
:::

The tasks we want you to do are:

1.  Download the files from the [data
    repository](https://github.com/seedcase-project/data/tree/main/patients).
2.  Open up the files on your computer and take a look at them, so you
    have a bit of an idea of what the data is.
3.  Using Sprout, create the metadata for the `patients.csv` file.
4.  Then create the metadata for `physical_activity_2023.csv` and call
    it `physical_activity`.
5.  Add the data from `physical_activity_2024.csv` to the
    `physical_activity` metadata.

Go through them one at the time and remember to verbally walk through
your thoughts and reactions to us.

Thank you so much for your help and your time! :relaxed:
