group:
  repos: |
    seedcase-project/seedcase-project
    seedcase-project/seedcase-registry
    seedcase-project/seedcase-theme
    seedcase-project/seedcase
  files:
    - source: .editorconfig
      dest: .editorconfig
    - source: .gitignore
      dest: .gitignore
    - source: .vscode/settings.json
      dest: .vscode/settings.json
    - source: .vscode/extensions.json
      dest: .vscode/extensions.json
