group:
  - files:
      - source: .github/CODEOWNERS
        dest: .github/CODEOWNERS
      - source: .editorconfig
        dest: .editorconfig
      - source: .gitignore
        dest: .gitignore
      - source: .vscode/settings.json
        dest: .vscode/settings.json
      - source: .vscode/extensions.json
        dest: .vscode/extensions.json
    repos: |
      seedcase-project/seedcase-project
      seedcase-project/seedcase-registry
      seedcase-project/seedcase-theme
      seedcase-project/seedcase
      steno-aarhus/sdca_admin
  - files:
      - source: common/python-style.yml
        dest: .github/workflows/python-style.yml
      - source: common/justfile-dev
        dest: justfile
    repos: |
      seedcase-project/seedcase-registry
      seedcase-project/seedcase
  - files:
      - source: common/justfile-web
        dest: justfile
    repos: |
      seedcase-project/seedcase-project
