project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Team Docs"
  site-url: "https://team.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/team"
  page-navigation: true
  navbar:
    title: false
    logo: _extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-team.svg
    logo-alt: "Seedcase Team logo: Main page"
    pinned: true
    left:
      - href: onboarding/index.qmd
      - href: how-we-work/index.qmd
      - text: Events
        href: events/index.qmd
    tools:
      - icon: house
        href: https://seedcase-project.org
        aria-label: "House icon: Seedcase Project home page"
      - icon: github
        href: "https://github.com/seedcase-project/team"
        aria-label: "GitHub icon: Source code"

format:
  seedcase-theme-html:
    include-before-body:
      - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
