---
title: "In-person meetings"
---

We are a remote-first group, but we also value the in-person time as a
way to get to know one another better, do some intensive brainstorming
and planning sessions, and just do some social activities together.

We plan on doing them approximately every 6 months, but we don't have a
fixed date for them. If there is a conference or other event that most
of us will attend, then we will plan the in-person time around that
event. Otherwise, we will just pick a time that works for most people,
maybe around April/May and October/November.

During the in-person time we all agree that we want to prioritise these
types of activities, in this order:

- Social activities to strengthen our relationships and get to know one
  another a bit more outside of a work context. Meaning, we don't do
  work related activities during these times. These activities could be
  dinners, going to museums, doing escape rooms, or other fun activities
  together. The team lead is responsible for book and planning these
  activities, though everyone gives their input on what they would like
  to do and what they think would be fun.

- Intensive brainstorming, eventstorming, and/or planning sessions.
  These types of sessions work best with in-person interaction because
  the questioning, discussing, and deciding feedback loop is much
  faster. These benefit from having a clear agenda beforehand, which is
  the responsibility of the team lead to prepare and share with the team
  before the in-person time.
