---
title: Onboarding
---

{{< include /includes/_wip.qmd >}}

## Welcome to Seedcase

If you landed on this post, you are most likely a new team member on the Seedcase Project. Welcome!

To get you started, there are some first steps you'll need to do and some posts for you to read and review.

## First steps

1. **Send your GitHub username and Discord username to the Team Leader**
    - We use Discord as our communication platform and this way so you can be added to the Seedcase Project server right away. If you don't have a Discord account, you can go to [discord.com](https://discord.com) and create one.
    - You will need to be added to the SDCA and Seedcase organizations (and potentially other repositories) on GitHub. If you don't have a GitHub account, you can go to [github.com](https://github.com) and create one.
2. **Set up GitHub two-factor authentication (2FA)**
    - See [this post](/how-we-work/github.qmd) (you will need 2FA to access the Seedcase repositories).
3. **Order IT equipment**
    - Talk to the Team Leader about which IT equipment you will need (e.g., computer, mouse, keyboard, and dock station) and Team Leader will help you with ordering it.

## Team calendars

We have a set of team calendars to schedule meetings, annual leave, iterations, and so on. For this, we use [Team Up](https://teamup.com/) calendars. Someone from the team will send you an invite link. You will need to create an account on teamup.com for this.

To get the calendars in your own calendar app, follow these instructions:

1. Go to [teamup.com](teamup.com) and log in.
2. Open the calendar that you want to subscribe to.
3. Click the blue menu button in the top right corner, select `Preferences` > `iCalendar Feeds`.
4. Select the calendar you want to subscribe to. You can choose to subscribe to calendars individually or select all of them in one go. Some of us prefer not to have all of them in our personal calendar, so it's up to you. 

    - Tip: If you subscribe to the calendars individually you can choose to only show e.g., the iteration calendar on your computer, but not on your phone.

5. Copy the URL and add it to your calendar app. How you do this depends on the app you use:
    
    - For Mac users: Open the Calendar app, go to `File` > `New Calendar Subscription`, paste the URL, and click `Subscribe`.

For more help, you can take a look at the guide on [Outbound iCalendar Feeds](https://calendar.teamup.com/kb/subscribe-to-teamup-icalendar-feeds/) in the Team Up Knowledge Base.


## Software

The [software we use](/how-we-work/software.qmd) post lists the software you will need to install in order to effectively contribute as part of the team. Go to the post and install the software listed there.

## Posts to read and review

In the Seedcase Project, we practice a "documentation first" culture. One of the things that means is that when you read through posts and encounter something that's unclear or information that's missing or outdated, we encourage you to create Issues (or Pull Requests) describing those issues you've found.

Therefore, before you start to read and review the pages in the list below, read the following posts
with introductions and guidelines to our workflows:

1. [Documentation First Culture](https://community.seedcase-project.org/guides/documentation-first/)
2. [Workflow for developing software and documentation](/how-we-work/workflow.qmd)
3. If you will need to add new posts, read the how-to ["Adding posts"](https://community.seedcase-project.org/guides/adding-posts/), which contains guidelines on that.

Now that you have read the above, you can review the pages below. As you review them, create any Issues in the respective GitHub repository (e.g. the `team` repo for things about the `team` website) for things you find confusing or unclear, if you have questions, or other suggestions for improvements.

1. [Onboarding SDCA website](https://steno-aarhus.github.io/research/onboarding.html): This website is for general onboarding at SDCA and covers general onboarding, such as the general code of conduct and details on varous social activities and events.
2. [Our Seedcase Team Docs website](https://team.seedcase-project.org/): This website is where this post is located and covers the documentation, contributing guidelines, onboarding material, and event details/agendas for the Seedcase Project team.
3. [General contributing guidelines website](https://community.seedcase-project.org/#contributing): This website covers some general contributing guidelines for the Seedcase Project.
4. [Community pages](https://community.seedcase-project.org/): This website is used for content we want people outside the team, like an external reader, to read and browse, such as the roadmap, outreach material, and events.
5. [Our Decisions Posts](https://decisions.seedcase-project.org/): This describes why we made the choices we did.
6. [Overall design documentation](https://design.seedcase-project.org): The design documentation covers stakeholders, design decisions, software architecture, data architecture, and more.

If something is unclear to you, you are more than welcome to reach out to the other team members on Discord. We'd love to help you out.
